### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by Momo90k** [attilaoroszdev/godoteuconsentparserplugin#2]
There is a spelling mistake with the word personalised both in the readme and in methods and signals. The right word to use is personalized with a "z".

**Comment by attilaoroszdev** [comment]
It's British spelling. (You know the original English.) 😃

Everything I write (apart from code) uses British variants (unless I've spent too much time reading American content, and slip up occasionally).

In code it's harder, since you mostly use the American variants (e.g. Godot's `Color` is missing a "u" (proper spelling is "colour" 😃 ) and I keep mixing stuff up in variable names, but the intention is usually to stick with what I know (the British variant).

Thanks for the heads up, though. 🙂

**Comment by attilaoroszdev** [comment]
Had a little read-through, and there are about 768.5 actual spelling mistakes in the README, *and* in the Godot script comments, too. (Just had to read it from a different screen and they popped right out.)

Reopening this, so I (hopefully) won't forget to fix them...

**Comment by Momo90k** [comment]
Ah. My bad. Sorry 😬

**Comment by attilaoroszdev** [comment]
Still a good thing came of it, I at least spotted the *other* spelling issues. 🙂 (And there are a lot.)

**Comment by Momo90k** [comment]
Accidental contribution to open source software.

**Comment by attilaoroszdev** [comment]
This is done, for now.
